# Generated by Django 5.2 on 2025-04-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('income', models.FloatField()),
                ('credit_score', models.IntegerField()),
                ('total_debt', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('employment_status', models.CharField(choices=[('Permanent', 'Permanent'), ('Self-Employed', 'Self-Employed'), ('Contract', 'Contract'), ('Unemployed', 'Unemployed')], max_length=20)),
                ('eligibility_result', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
